package com.jdedwards.system.connector.dynamic.sample.events;
/*
 * SrcFrame.java
 *
 * Created on August 23, 2000, 11:58 AM
 */
 
import java.io.*;
import javax.swing.*;

/** 
 *
 * @author  KK949259
 * @version
 * @testcase test.com.jdedwards.system.connector.dynamic.sample.events.TestSrcFrame 
 */
public class SrcFrame extends JFrame {

  /** Creates new form SrcFrame */
  public SrcFrame() {    
    
    initComponents ();    
    pack ();
    resize(600,420);
    
    
    populateEventTypes();
    
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
private void initComponents() {//GEN-BEGIN:initComponents
ComboBoxEventTypes = new JComboBox();
EventTypeLabel = new JLabel();
SendButton = new JButton();
PortField = new JTextField();
jLabel2 = new JLabel();
jLabel3 = new JLabel();
jLabel4 = new JLabel();
jLabel5 = new JLabel();
HostField = new JTextField();
TimeoutField = new JTextField();
jLabel1 = new JLabel();
FileField = new JTextField();
jLabel6 = new JLabel();
FileOpenButton = new JButton();
EnvironField = new JTextField();
jLabel7 = new JLabel();
jTextField1 = new JTextField();
threadsTextField = new JTextField();
callsTextField = new JTextField();
getContentPane().setLayout(null);
setTitle("Event source");
addWindowListener(new java.awt.event.WindowAdapter() {
public void windowClosing(java.awt.event.WindowEvent evt) {
exitForm(evt);
}
}
);

ComboBoxEventTypes.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
ComboBoxEventTypesActionPerformed(evt);
}
}
);

getContentPane().add(ComboBoxEventTypes);
ComboBoxEventTypes.setBounds(10, 40, 180, 20);


EventTypeLabel.setText("Event Type:");
EventTypeLabel.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(EventTypeLabel);
EventTypeLabel.setBounds(10, 10, 170, 20);


SendButton.setLabel("Send");
SendButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
onSend(evt);
}
}
);

getContentPane().add(SendButton);
SendButton.setBounds(310, 340, 140, 30);


PortField.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
PortFieldActionPerformed(evt);
}
}
);

getContentPane().add(PortField);
PortField.setBounds(10, 210, 180, 30);


jLabel2.setText("Threads");
jLabel2.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel2);
jLabel2.setBounds(250, 30, 60, 20);


jLabel3.setText("Calls Per Thread");
jLabel3.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel3);
jLabel3.setBounds(250, 80, 100, 20);


jLabel4.setText("Host");
jLabel4.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel4);
jLabel4.setBounds(10, 130, 170, 20);


jLabel5.setText("Port");
jLabel5.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel5);
jLabel5.setBounds(10, 190, 180, 20);



getContentPane().add(HostField);
HostField.setBounds(10, 150, 180, 30);



getContentPane().add(TimeoutField);
TimeoutField.setBounds(10, 270, 180, 30);


jLabel1.setText("Timeout");
jLabel1.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel1);
jLabel1.setBounds(10, 250, 180, 20);


FileField.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
FileFieldActionPerformed(evt);
}
}
);

getContentPane().add(FileField);
FileField.setBounds(10, 340, 180, 30);


jLabel6.setText("XML File");
jLabel6.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel6);
jLabel6.setBounds(10, 320, 180, 20);


FileOpenButton.setText("Open...");
FileOpenButton.addActionListener(new java.awt.event.ActionListener() {
public void actionPerformed(java.awt.event.ActionEvent evt) {
onFileOpen(evt);
}
}
);

getContentPane().add(FileOpenButton);
FileOpenButton.setBounds(200, 340, 80, 30);



getContentPane().add(EnvironField);
EnvironField.setBounds(10, 100, 180, 30);


jLabel7.setText("Environment");
jLabel7.setFont(new java.awt.Font ("Dialog", 1, 11));

getContentPane().add(jLabel7);
jLabel7.setBounds(10, 80, 180, 20);


jTextField1.setText("jTextField1");

getContentPane().add(jTextField1);
jTextField1.setBounds(300, 20, -230, 0);



getContentPane().add(threadsTextField);
threadsTextField.setBounds(360, 30, 130, 30);



getContentPane().add(callsTextField);
callsTextField.setBounds(360, 80, 130, 30);

}//GEN-END:initComponents

  private void FileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileFieldActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_FileFieldActionPerformed

  private void onFileOpen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onFileOpen
    JFileChooser dlg = new JFileChooser();
    if( JFileChooser.APPROVE_OPTION == dlg.showOpenDialog(this))
    {
        File file = dlg.getSelectedFile();
        if( null != file )
        {
            FileField.setText(file.getAbsolutePath());
        }
    }
  }//GEN-LAST:event_onFileOpen

  private void ComboBoxEventTypesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEventTypesActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_ComboBoxEventTypesActionPerformed

  private void PortFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortFieldActionPerformed
// Add your handling code here:
  }//GEN-LAST:event_PortFieldActionPerformed

  private void onSend(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onSend
    
      try
      {
          String env = EnvironField.getText();
          String host = HostField.getText();
          int    port = Integer.parseInt(PortField.getText());
          String EventType = (String)ComboBoxEventTypes.getSelectedItem();
          int    timeout = Integer.parseInt(TimeoutField.getText());
          String docFile = FileField.getText();
          File f = new File(docFile);
          char[] c = new char[(int)f.length()];
          FileReader inp = new FileReader(f);
          inp.read(c, 0, (int)f.length());
          inp.close();
          String xmlString = new String(c);
          int calls;
          int threads;
          try
          {
            threads = Integer.parseInt(threadsTextField.getText());
          }
          catch(Exception e)
          {
              threads = 1;
          }
          try
          {
            calls = Integer.parseInt(callsTextField.getText());
          }
          catch(Exception e)
          {
              calls = 1;
          }
          threads = Math.max(threads,1);
          calls   = Math.max(calls,1);


//          TRequest theRequest = new TRequest(host, port, xmlString, EventType, timeout);
//          theRequest.send();
          
          EventData eventdata = new EventData(host, env, EventType, xmlString, port, timeout, threads, calls);
          
          for(int i=0; i<threads; i++)
          {
            new EventJob(eventdata).start();
          }
      }
      catch(Exception e)
      {
          System.out.println(e.toString());
      }
  }//GEN-LAST:event_onSend

  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm

  /**
  * @param args the command line arguments
  */
  public static void main (String[] args) {
    new SrcFrame ().show ();
  }


// Variables declaration - do not modify//GEN-BEGIN:variables
private JComboBox ComboBoxEventTypes;
private JLabel EventTypeLabel;
private JButton SendButton;
private JTextField PortField;
private JLabel jLabel2;
private JLabel jLabel3;
private JLabel jLabel4;
private JLabel jLabel5;
private JTextField HostField;
private JTextField TimeoutField;
private JLabel jLabel1;
private JTextField FileField;
private JLabel jLabel6;
private JButton FileOpenButton;
private JTextField EnvironField;
private JLabel jLabel7;
private JTextField jTextField1;
private JTextField threadsTextField;
private JTextField callsTextField;
// End of variables declaration//GEN-END:variables

  private void populateEventTypes()
  {
    String eventStr = null;
    try
    {
      BufferedReader ini = new BufferedReader( new FileReader(System.getProperty("EVENTS_FILE")) );
      while( null != (eventStr = ini.readLine()) )
      {
        ComboBoxEventTypes.addItem(eventStr);
      }
    }
    catch(Exception e)
    {
    }
  }
  
  
  
}